BinaryTreeMain: BinaryTreeMain.o BinaryTree.o
	gcc -o BinaryTreeMain BinaryTreeMain.o BinaryTree.o
BinaryTreeMain.o : BinaryTree.h BinaryTreeMain.c
	gcc -c BinaryTreeMain.c # -c : make object file
BinaryTree.o : BinaryTree.h BinaryTree.c
	gcc -c BinaryTree.c
